#
# Package name
#

NAME=RNBasics



#
# List of source files
#

CCSRCS=$(NAME).cpp \
	RNTime.cpp \
        RNGrfx.cpp RNRgb.cpp \
        RNMap.cpp RNHeap.cpp RNQueue.cpp RNArray.cpp \
	RNSvd.cpp RNIntval.cpp RNScalar.cpp \
 	RNType.cpp \
 	RNFlags.cpp \
        RNFile.cpp RNMem.cpp \
	RNError.cpp \
	RNBase.cpp \
        json.cpp



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs



