#
# Package name
#

NAME=RGBD



#
# List of source files
#

CCSRCS=RGBD.cpp \
    RGBDTransform.cpp \
    RGBDConfiguration.cpp \
    RGBDSurface.cpp RGBDImage.cpp \
    RGBDCamera.cpp RGBDUtil.cpp


#
# Dependencies
#

PKG_DEPENDENCIES = R3Shapes R2Shapes RNBasics jpeg png



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs







