#
# Package name
#

NAME=R2Shapes



#
# List of source files
#

CCSRCS=R2Shapes.cpp \
    R2Draw.cpp R2Io.cpp R2Kdtree.cpp \
    R2Dist.cpp R2Cont.cpp R2Isect.cpp R2Parall.cpp R2Perp.cpp R2Relate.cpp R2Align.cpp \
    R2Grid.cpp \
    R2Polyline.cpp R2Arc.cpp R2Curve.cpp \
    R2Polygon.cpp R2Circle.cpp R2Box.cpp R2Solid.cpp \
    R2Shape.cpp \
    R2Affine.cpp R2Xform.cpp R2Crdsys.cpp R2Diad.cpp R3Matrix.cpp \
    R2Halfspace.cpp R2Span.cpp R2Ray.cpp R2Line.cpp R2Point.cpp R2Vector.cpp \
    R2Image.cpp


#
# Dependencies
#

PKG_DEPENDENCIES = RNBasics jpeg png



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs







