#
# Application name and list of source files.
#

NAME=mpview
CCSRCS=$(NAME).cpp mp.cpp


#
# Dependency libraries
#

PKG_LIBS=-lRGBD -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


