#
# Package name
#

NAME=R3Shapes



#
# List of source files
#

CCSRCS=$(NAME).cpp \
    R3Draw.cpp \
    R3MeshSearchTree.cpp R3MeshPropertySet.cpp R3MeshProperty.cpp \
    R3Isect.cpp R3Cont.cpp R3Dist.cpp R3Parall.cpp R3Perp.cpp R3Relate.cpp R3Align.cpp R3Kdtree.cpp \
    R3CatmullRomSpline.cpp R3Polyline.cpp R3Curve.cpp \
    R3Mesh.cpp R3Rectangle.cpp R3Ellipse.cpp R3Circle.cpp R3TriangleArray.cpp R3Triangle.cpp R3Surface.cpp \
    R3Ellipsoid.cpp R3Sphere.cpp R3Cone.cpp R3Cylinder.cpp R3OrientedBox.cpp R3Box.cpp R3Solid.cpp \
    R3Shape.cpp \
    R3Affine.cpp R3Xform.cpp R3Crdsys.cpp R3Triad.cpp R3Quaternion.cpp R4Matrix.cpp \
    R3PlanarGrid.cpp R3Grid.cpp \
    R3Halfspace.cpp R3Plane.cpp R3Span.cpp R3Ray.cpp R3Line.cpp R3Point.cpp R3Vector.cpp \
    R3Base.cpp \
    ply.cpp


#
# Dependencies
#

PKG_DEPENDENCIES = R2Shapes RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs









