#
# Package name
#

NAME=png



#
# List of source files
#

# JPEG library source files
PNG_CSRCS = \
  png.c \
  pngset.c \
  pngget.c \
  pngrutil.c \
  pngtrans.c \
  pngwutil.c \
  pngread.c \
  pngrio.c \
  pngwio.c \
  pngwrite.c \
  pngrtran.c \
  pngwtran.c \
  pngmem.c \
  pngerror.c \
  pngpread.c 

ZLIB_CSRCS = \
  adler32.c \
  compress.c \
  crc32.c \
  deflate.c \
  gzclose.c \
  gzlib.c \
  gzread.c \
  gzwrite.c \
  infback.c \
  inffast.c \
  inflate.c \
  inftrees.c \
  trees.c \
  uncompr.c \
  zutil.c

CSRCS = $(PNG_CSRCS) $(ZLIB_CSRCS)



#
# GAPS library makefile
#

include ../../makefiles/Makefile.pkgs



