#
# Package name
#

NAME=R3Graphics



#
# List of source files
#

CCSRCS=$(NAME).cpp \
    R3Scene.cpp R3SceneNode.cpp R3SceneElement.cpp R3SceneReference.cpp \
    R3Viewer.cpp R3Frustum.cpp R3Camera.cpp R2Viewport.cpp \
    R3AreaLight.cpp R3SpotLight.cpp R3PointLight.cpp R3DirectionalLight.cpp R3Light.cpp \
    R3Material.cpp R3Brdf.cpp R2Texture.cpp



#
# Dependencies
#

PKG_DEPENDENCIES = R3Shapes R2Shapes RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs




